# Generated by Django 4.2.21 on 2025-05-29 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Elder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=10, verbose_name='性别')),
                ('address', models.TextField(verbose_name='居住地址')),
                ('phone', models.CharField(max_length=15, verbose_name='联系电话')),
                ('medical_history', models.TextField(blank=True, verbose_name='病史')),
                ('emergency_contact', models.CharField(max_length=50, verbose_name='紧急联系人')),
                ('emergency_phone', models.CharField(max_length=15, verbose_name='紧急联系电话')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '老人信息',
                'verbose_name_plural': '老人信息',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('family', '家属'), ('caregiver', '护工'), ('doctor', '医生'), ('admin', '管理员')], max_length=20, verbose_name='用户类型')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='手机号')),
                ('department', models.CharField(blank=True, max_length=50, verbose_name='部门/科室')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='最后登录IP')),
                ('related_elder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zhyanglao_app.elder', verbose_name='关联老人')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
        migrations.CreateModel(
            name='HealthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='记录时间')),
                ('heart_rate', models.IntegerField(blank=True, null=True, verbose_name='心率')),
                ('blood_pressure_sys', models.IntegerField(blank=True, null=True, verbose_name='收缩压')),
                ('blood_pressure_dia', models.IntegerField(blank=True, null=True, verbose_name='舒张压')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='体温')),
                ('sleep_quality', models.CharField(blank=True, max_length=20, null=True, verbose_name='睡眠质量')),
                ('activity_level', models.CharField(blank=True, max_length=20, null=True, verbose_name='活动量')),
                ('elder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zhyanglao_app.elder', verbose_name='老人')),
            ],
            options={
                'verbose_name': '健康数据',
                'verbose_name_plural': '健康数据',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='设备名称')),
                ('device_type', models.CharField(choices=[('camera', '摄像头'), ('sensor', '传感器'), ('switch', '智能开关'), ('lock', '智能门锁'), ('other', '其他设备')], max_length=20, verbose_name='设备类型')),
                ('brand', models.CharField(max_length=50, verbose_name='品牌')),
                ('model', models.CharField(max_length=50, verbose_name='型号')),
                ('location', models.CharField(max_length=100, verbose_name='安装位置')),
                ('device_id', models.CharField(max_length=100, unique=True, verbose_name='设备ID')),
                ('status', models.BooleanField(default=True, verbose_name='设备状态')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('last_active', models.DateTimeField(blank=True, null=True, verbose_name='最后活跃时间')),
                ('elder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zhyanglao_app.elder', verbose_name='所属老人')),
            ],
            options={
                'verbose_name': '智能设备',
                'verbose_name_plural': '智能设备',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=50, verbose_name='告警类型')),
                ('alert_level', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '紧急')], max_length=20, verbose_name='告警级别')),
                ('description', models.TextField(verbose_name='告警描述')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='告警时间')),
                ('processed', models.BooleanField(default=False, verbose_name='是否处理')),
                ('processed_time', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zhyanglao_app.device', verbose_name='触发设备')),
                ('elder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zhyanglao_app.elder', verbose_name='老人')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
            ],
            options={
                'verbose_name': '告警记录',
                'verbose_name_plural': '告警记录',
            },
        ),
        migrations.CreateModel(
            name='AIInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='交互时间')),
                ('query', models.TextField(verbose_name='用户问题')),
                ('response', models.TextField(verbose_name='AI回答')),
                ('feedback', models.IntegerField(blank=True, choices=[(1, '不满意'), (2, '一般'), (3, '满意')], null=True, verbose_name='满意度')),
                ('elder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zhyanglao_app.elder', verbose_name='老人')),
            ],
            options={
                'verbose_name': 'AI交互记录',
                'verbose_name_plural': 'AI交互记录',
            },
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='报告日期')),
                ('health_summary', models.TextField(verbose_name='健康概况')),
                ('activity_summary', models.TextField(verbose_name='活动概况')),
                ('alert_summary', models.TextField(blank=True, verbose_name='异常情况汇总')),
                ('ai_suggestions', models.TextField(blank=True, verbose_name='AI建议')),
                ('elder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zhyanglao_app.elder', verbose_name='老人')),
            ],
            options={
                'verbose_name': '每日报告',
                'verbose_name_plural': '每日报告',
                'unique_together': {('elder', 'date')},
            },
        ),
    ]
