# Generated by Django 5.2.1 on 2025-06-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhyanglao_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('family', '家属'), ('caregiver', '护工'), ('doctor', '医生'), ('admin', '管理员'), ('elderly', '老人')], max_length=20, verbose_name='用户类型'),
        ),
    ]
