# Generated by Django 4.2.21 on 2025-06-08 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zhyanglao_app', '0002_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElderAssociationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elder_name', models.CharField(max_length=50, verbose_name='老人姓名')),
                ('elder_phone', models.CharField(max_length=15, verbose_name='老人联系电话')),
                ('elder_address', models.TextField(verbose_name='老人居住地址')),
                ('relationship', models.CharField(choices=[('子女', '子女'), ('配偶', '配偶'), ('孙辈', '孙辈'), ('其他亲属', '其他亲属')], max_length=20, verbose_name='与老人关系')),
                ('request_reason', models.TextField(verbose_name='申请原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('approved', '已批准'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('elder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zhyanglao_app.elder', verbose_name='关联老人')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_requests', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elder_requests', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '老人关联申请',
                'verbose_name_plural': '老人关联申请',
                'ordering': ['-created_at'],
            },
        ),
    ]
