# Generated by Django 5.2.1 on 2025-06-18 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zhyanglao_app', '0004_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
